#!/bin/bash

NAME=$1
TYPE='controller'
TYPEX='ctrl'
CTRLPATH=js/controllers/
EXT='js'

TEMPLATE=$(cat <<EndoL
/**
 * Description goes here
 * @return null
 * @author Kenneth 'digiArtist_ph' P. Vallejos
 * @since 
 *
 */
angular.module('${NAME}.${TYPE}', [])

.controller('${NAME^}${TYPEX^}', ['\$scope', function(\$scope) {
   \$scope.data = [];
}]);
EndoL
)

# prints to file
echo "${TEMPLATE}" > $CTRLPATH${NAME}.${TYPE}.${EXT}
