#!/bin/bash

NAME=$1
TYPE='view'
TYPEX='vw'
VWPATH=./
EXT='html'

TEMPLATE=$( cat <<EndoL
<!DOCTYPE html>
<html lang="en" ng-app="ngApp">
<head>
   <meta charset="UTF-8">
   <title>Sample UI-Router</title>

   <!-- css here -->

   <script src="libs/angular/angular.min.js"></script>
   <script src="libs/angular-ui-router/release/angular-ui-router.min.js"></script>

   <!-- angular scripts here -->
   <script src="js/app.js"></script>

   <!-- other javascripts here -->
</head>
<body>
   <div class="container" ui-view></div>
   
   <!-- other javascripts here -->

</body>
</html>
EndoL
)

# prints to file
echo "${TEMPLATE}" > $VWPATH${NAME}.${EXT}
