#!/bin/bash

NAME=$1
TYPE='view'
TYPEX='vw'
VWPATH=templates/
EXT='html'

TEMPLATE=$( cat <<EndoL
<div class="container">
   <h1>Template View</h1>
</div>
EndoL
)

# prints to file
echo "${TEMPLATE}" > $VWPATH${NAME}.${TYPE}.${EXT}

