<?php 
// echo '<?xml version="1.0" encoding="UTF-8"'?>
<!--<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
   <url>
      <loc>https://www.terrigal.com.au/</loc>
      <priority>0.5</priority>
   </url>
   <url>
      <loc>https://www.terrigal.com.au/register</loc>
      <priority>0.5</priority>
   </url>
   <url>
      <loc>https://www.terrigal.com.au/login</loc>
      <priority>0.5</priority>
   </url>
   <url>
      <loc>https://www.terrigal.com.au/about-us</loc>
      <priority>0.5</priority>
   </url>
   <url>
      <loc>https://www.terrigal.com.au/contact-us</loc>
      <priority>0.5</priority>
   </url>
   <url>
      <loc>https://www.terrigal.com.au/faqs</loc>
      <priority>0.5</priority>
   </url>
   <url>
      <loc>https://www.terrigal.com.au/feedback</loc>
      <priority>0.5</priority>
   </url>
   <url>
      <loc>https://www.terrigal.com.au/listing</loc>
      <priority>0.5</priority>
   </url>
   <url>
      <loc>https://www.terrigal.com.au/terms-of-service</loc>
      <priority>0.5</priority>
   </url>
   <url>
      <loc>https://www.terrigal.com.au/privacy-policy</loc>
      <priority>0.5</priority>
   </url>
   <url>
      <loc>https://www.terrigal.com.au/forgot-password</loc>
      <priority>0.5</priority>
   </url>
   <url>
      <loc>https://www.terrigal.com.au/food</loc>
      <priority>0.5</priority>
   </url>
   <url>
      <loc>https://www.terrigal.com.au/accommodation</loc>
      <priority>0.5</priority>
   </url>
   <url>
      <loc>https://www.terrigal.com.au/services</loc>
      <priority>0.5</priority>
   </url>
   <url>
      <loc>https://www.terrigal.com.au/retailer</loc>
      <priority>0.5</priority>
   </url>
   <url>
      <loc>https://www.terrigal.com.au/real-estate</loc>
      <priority>0.5</priority>
   </url>
   <url>
      <loc>https://www.terrigal.com.au/sports</loc>
      <priority>0.5</priority>
   </url>
   <url>
      <loc>https://www.terrigal.com.au/fitness</loc>
      <priority>0.5</priority>
   </url>
   <url>
      <loc>https://www.terrigal.com.au/financial</loc>
      <priority>0.5</priority>
   </url>
   <url>
      <loc>https://www.terrigal.com.au/events</loc>
      <priority>0.5</priority>
   </url>
   <url>
      <loc>https://www.terrigal.com.au/medical</loc>
      <priority>0.5</priority>
   </url>-->
    <?php
        $counter = 1;
        foreach ($businesses as $business) {
            echo $counter.'.) '.$business->business_permalink.'<br>';
            $counter++;
        }
    ?>
<!--</urlset>-->